services:
  postgres:
    image: postgres:15-alpine
    container_name: sahakar_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: VqVzHScRLdNyCYlq
      POSTGRES_DB: sahakar_ppo_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    container_name: sahakar_redis
    ports:
      - "6379:6379"

volumes:
  postgres_data:
